import type { Metadata } from "next"
import { Geist_Mono, Timmana, Public_Sans } from "next/font/google"
import "./globals.css"

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const timmana = Timmana({
  variable: "--font-timmana",
  weight: ["400"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Fintrack Test - Osaretin Osariemen Frank",
  description: "Generated by Osaretin Osariemen Frank",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${publicSans.variable} ${geistMono.variable} ${timmana.variable} antialiased overflow-x-hidden text-[#1B2528]`}
      >
        <div className="main-app">{children}</div>
      </body>
    </html>
  )
}
